language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"
  - DJANGO="Django<1.11"
  - DJANGO="Django<2"
  - DJANGO="Django<2.1"
  - DJANGO="Django<2.2"

install:
  - pip install $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO="Django<1.10"
      python: "3.3"
    - env: DJANGO="Django<1.10"
      python: "pypy3"
    - env: DJANGO="Django<1.11"
      python: "3.3"
    - env: DJANGO="Django<1.11"
      python: "pypy3"
